// <auto-generated />
using System;
using DasTeamRevolution.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DasTeamRevolution.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210428131210_CreatedCustomerSupplierAndSupplierUserPermissionJunctionTables")]
    partial class CreatedCustomerSupplierAndSupplierUserPermissionJunctionTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DasTeamRevolution.Data.Models.ApplicationUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("CreatedOn");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FirstName");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit")
                        .HasColumnName("IsAdmin");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LastName");

                    b.Property<DateTime?>("NewPasswordRequiredOn")
                        .HasColumnType("date")
                        .HasColumnName("NewPasswordRequiredOn");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Password");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("ApplicationUser");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.Assignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrderId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("OrderId");

                    b.ToTable("Assignment");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("CreationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Fax");

                    b.Property<long?>("GroupId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LastModificationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Phone");

                    b.Property<long?>("PostalAddressId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreationId");

                    b.HasIndex("GroupId");

                    b.HasIndex("LastModificationId");

                    b.HasIndex("PostalAddressId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.CustomerGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("CreationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("HeaderId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LastModificationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreationId");

                    b.HasIndex("HeaderId");

                    b.HasIndex("LastModificationId");

                    b.HasIndex("ParentId");

                    b.ToTable("CustomerGroup");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.CustomerHeader", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("CustomerHeader");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.CustomerHeaderAdmin", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("AdminId")
                        .HasColumnType("bigint")
                        .HasColumnName("AdminId");

                    b.Property<long>("CustomerHeaderId")
                        .HasColumnType("bigint")
                        .HasColumnName("CustomerHeaderId");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("CustomerHeaderId");

                    b.ToTable("CustomerHeaderAdmin");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.CustomerProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("CustomerId");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("ProfileId");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProfileId");

                    b.ToTable("CustomerProfile");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.CustomerSupplier", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("CustomerId");

                    b.Property<long>("SupplierId")
                        .HasColumnType("bigint")
                        .HasColumnName("SupplierId");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SupplierId");

                    b.ToTable("CustomerSupplier");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.CustomerUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ApplicationUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("ApplicationUserId");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("CustomerUser");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.CustomerUserPermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("CustomerId");

                    b.Property<long>("CustomerUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("CustomerUserId");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("CustomerUserId");

                    b.ToTable("CustomerUserPermission");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.Dossier", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SupplierUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("VacancyId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("SupplierUserId");

                    b.HasIndex("VacancyId");

                    b.ToTable("Dossier");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.DossierState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("CreationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DossierId")
                        .HasColumnType("bigint");

                    b.Property<int>("StateType")
                        .HasColumnType("int")
                        .HasColumnName("StateType");

                    b.HasKey("Id");

                    b.HasIndex("CreationId");

                    b.HasIndex("DossierId");

                    b.ToTable("DossierState");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("CreationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LastModificationId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreationId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LastModificationId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.PostalAddress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryCodeISO")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("CountryCodeISO");

                    b.Property<string>("PostalCity")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("PostalCity");

                    b.Property<string>("PostalName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("PostalName");

                    b.Property<string>("PostalStreet")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("PostalStreet");

                    b.Property<string>("PostalZipCode")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("PostalZipCode");

                    b.HasKey("Id");

                    b.HasIndex("CountryCodeISO");

                    b.HasIndex("PostalZipCode", "PostalCity");

                    b.ToTable("PostalAddress");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.Profile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Profile");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.Rating", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("AssignmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("AssignmentId");

                    b.Property<long?>("CreationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CustomerUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LastModificationId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId")
                        .IsUnique();

                    b.HasIndex("CreationId");

                    b.HasIndex("CustomerUserId");

                    b.HasIndex("LastModificationId");

                    b.ToTable("Rating");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.RecordCreation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedOn");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("RecordCreation");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.RecordModification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("ModifiedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedOn");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Reason");

                    b.HasKey("Id");

                    b.HasIndex("ModifiedById");

                    b.ToTable("RecordModification");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.Supplier", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("CreationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LastModificationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PostalAddressId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreationId");

                    b.HasIndex("LastModificationId");

                    b.HasIndex("PostalAddressId");

                    b.ToTable("Supplier");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.SupplierUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ApplicationUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("ApplicationUserId");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("SupplierUser");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.SupplierUserPermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("SupplierId")
                        .HasColumnType("bigint")
                        .HasColumnName("SupplierId");

                    b.Property<long>("SupplierUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("SupplierUserId");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.HasIndex("SupplierUserId");

                    b.ToTable("SupplierUserPermission");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.TimeRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("AssignmentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CustomerUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LastModificationId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("CreationId");

                    b.HasIndex("CustomerUserId");

                    b.HasIndex("LastModificationId");

                    b.ToTable("TimeRecord");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.TimeRecordState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("CreationId")
                        .HasColumnType("bigint");

                    b.Property<int>("StateType")
                        .HasColumnType("int")
                        .HasColumnName("StateType");

                    b.Property<long?>("TimeRecordId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreationId");

                    b.HasIndex("TimeRecordId");

                    b.ToTable("TimeRecordState");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.Vacancy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("CreationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LastModificationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PostalAddressId")
                        .HasColumnType("bigint");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Slug");

                    b.HasKey("Id");

                    b.HasIndex("CreationId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LastModificationId");

                    b.HasIndex("PostalAddressId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasFilter("[Slug] IS NOT NULL");

                    b.ToTable("Vacancy");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.VacancyState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("CreationId")
                        .HasColumnType("bigint");

                    b.Property<int>("StateType")
                        .HasColumnType("int")
                        .HasColumnName("StateType");

                    b.Property<long?>("VacancyId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreationId");

                    b.HasIndex("VacancyId");

                    b.ToTable("VacancyStates");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.Assignment", b =>
                {
                    b.HasOne("DasTeamRevolution.Data.Models.Employee", "Employee")
                        .WithMany("Assignments")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("DasTeamRevolution.Data.Models.Order", "Order")
                        .WithMany("Assignments")
                        .HasForeignKey("OrderId");

                    b.Navigation("Employee");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.Customer", b =>
                {
                    b.HasOne("DasTeamRevolution.Data.Models.RecordCreation", "Creation")
                        .WithMany()
                        .HasForeignKey("CreationId");

                    b.HasOne("DasTeamRevolution.Data.Models.CustomerGroup", "Group")
                        .WithMany("Customers")
                        .HasForeignKey("GroupId");

                    b.HasOne("DasTeamRevolution.Data.Models.RecordModification", "LastModification")
                        .WithMany()
                        .HasForeignKey("LastModificationId");

                    b.HasOne("DasTeamRevolution.Data.Models.PostalAddress", "PostalAddress")
                        .WithMany()
                        .HasForeignKey("PostalAddressId");

                    b.Navigation("Creation");

                    b.Navigation("Group");

                    b.Navigation("LastModification");

                    b.Navigation("PostalAddress");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.CustomerGroup", b =>
                {
                    b.HasOne("DasTeamRevolution.Data.Models.RecordCreation", "Creation")
                        .WithMany()
                        .HasForeignKey("CreationId");

                    b.HasOne("DasTeamRevolution.Data.Models.CustomerHeader", "Header")
                        .WithMany()
                        .HasForeignKey("HeaderId");

                    b.HasOne("DasTeamRevolution.Data.Models.RecordModification", "LastModification")
                        .WithMany()
                        .HasForeignKey("LastModificationId");

                    b.HasOne("DasTeamRevolution.Data.Models.CustomerGroup", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Creation");

                    b.Navigation("Header");

                    b.Navigation("LastModification");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.CustomerHeaderAdmin", b =>
                {
                    b.HasOne("DasTeamRevolution.Data.Models.ApplicationUser", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DasTeamRevolution.Data.Models.CustomerHeader", "CustomerHeader")
                        .WithMany()
                        .HasForeignKey("CustomerHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("CustomerHeader");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.CustomerProfile", b =>
                {
                    b.HasOne("DasTeamRevolution.Data.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DasTeamRevolution.Data.Models.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.CustomerSupplier", b =>
                {
                    b.HasOne("DasTeamRevolution.Data.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DasTeamRevolution.Data.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.CustomerUser", b =>
                {
                    b.HasOne("DasTeamRevolution.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithOne("CustomerUserId")
                        .HasForeignKey("DasTeamRevolution.Data.Models.CustomerUser", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.CustomerUserPermission", b =>
                {
                    b.HasOne("DasTeamRevolution.Data.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DasTeamRevolution.Data.Models.CustomerUser", "CustomerUser")
                        .WithMany()
                        .HasForeignKey("CustomerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("CustomerUser");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.Dossier", b =>
                {
                    b.HasOne("DasTeamRevolution.Data.Models.Employee", "Employee")
                        .WithMany("Dossiers")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("DasTeamRevolution.Data.Models.SupplierUser", "SupplierUser")
                        .WithMany()
                        .HasForeignKey("SupplierUserId");

                    b.HasOne("DasTeamRevolution.Data.Models.Vacancy", null)
                        .WithMany("Dossiers")
                        .HasForeignKey("VacancyId");

                    b.Navigation("Employee");

                    b.Navigation("SupplierUser");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.DossierState", b =>
                {
                    b.HasOne("DasTeamRevolution.Data.Models.RecordCreation", "Creation")
                        .WithMany()
                        .HasForeignKey("CreationId");

                    b.HasOne("DasTeamRevolution.Data.Models.Dossier", "Dossier")
                        .WithMany("States")
                        .HasForeignKey("DossierId");

                    b.Navigation("Creation");

                    b.Navigation("Dossier");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.Order", b =>
                {
                    b.HasOne("DasTeamRevolution.Data.Models.RecordCreation", "Creation")
                        .WithMany()
                        .HasForeignKey("CreationId");

                    b.HasOne("DasTeamRevolution.Data.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId");

                    b.HasOne("DasTeamRevolution.Data.Models.RecordModification", "LastModification")
                        .WithMany()
                        .HasForeignKey("LastModificationId");

                    b.Navigation("Creation");

                    b.Navigation("Customer");

                    b.Navigation("LastModification");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.Rating", b =>
                {
                    b.HasOne("DasTeamRevolution.Data.Models.Assignment", "Assignment")
                        .WithOne("Rating")
                        .HasForeignKey("DasTeamRevolution.Data.Models.Rating", "AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DasTeamRevolution.Data.Models.RecordCreation", "Creation")
                        .WithMany()
                        .HasForeignKey("CreationId");

                    b.HasOne("DasTeamRevolution.Data.Models.CustomerUser", "CustomerUser")
                        .WithMany("Ratings")
                        .HasForeignKey("CustomerUserId");

                    b.HasOne("DasTeamRevolution.Data.Models.RecordModification", "LastModification")
                        .WithMany()
                        .HasForeignKey("LastModificationId");

                    b.Navigation("Assignment");

                    b.Navigation("Creation");

                    b.Navigation("CustomerUser");

                    b.Navigation("LastModification");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.RecordCreation", b =>
                {
                    b.HasOne("DasTeamRevolution.Data.Models.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.RecordModification", b =>
                {
                    b.HasOne("DasTeamRevolution.Data.Models.ApplicationUser", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.Supplier", b =>
                {
                    b.HasOne("DasTeamRevolution.Data.Models.RecordCreation", "Creation")
                        .WithMany()
                        .HasForeignKey("CreationId");

                    b.HasOne("DasTeamRevolution.Data.Models.RecordModification", "LastModification")
                        .WithMany()
                        .HasForeignKey("LastModificationId");

                    b.HasOne("DasTeamRevolution.Data.Models.PostalAddress", "PostalAddress")
                        .WithMany()
                        .HasForeignKey("PostalAddressId");

                    b.Navigation("Creation");

                    b.Navigation("LastModification");

                    b.Navigation("PostalAddress");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.SupplierUser", b =>
                {
                    b.HasOne("DasTeamRevolution.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithOne("SupplierUser")
                        .HasForeignKey("DasTeamRevolution.Data.Models.SupplierUser", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.SupplierUserPermission", b =>
                {
                    b.HasOne("DasTeamRevolution.Data.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DasTeamRevolution.Data.Models.SupplierUser", "SupplierUser")
                        .WithMany()
                        .HasForeignKey("SupplierUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");

                    b.Navigation("SupplierUser");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.TimeRecord", b =>
                {
                    b.HasOne("DasTeamRevolution.Data.Models.Assignment", "Assignment")
                        .WithMany("TimeRecords")
                        .HasForeignKey("AssignmentId");

                    b.HasOne("DasTeamRevolution.Data.Models.RecordCreation", "Creation")
                        .WithMany()
                        .HasForeignKey("CreationId");

                    b.HasOne("DasTeamRevolution.Data.Models.CustomerUser", "CustomerUser")
                        .WithMany("TimeRecords")
                        .HasForeignKey("CustomerUserId");

                    b.HasOne("DasTeamRevolution.Data.Models.RecordModification", "LastModification")
                        .WithMany()
                        .HasForeignKey("LastModificationId");

                    b.Navigation("Assignment");

                    b.Navigation("Creation");

                    b.Navigation("CustomerUser");

                    b.Navigation("LastModification");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.TimeRecordState", b =>
                {
                    b.HasOne("DasTeamRevolution.Data.Models.RecordCreation", "Creation")
                        .WithMany()
                        .HasForeignKey("CreationId");

                    b.HasOne("DasTeamRevolution.Data.Models.TimeRecord", "TimeRecord")
                        .WithMany("States")
                        .HasForeignKey("TimeRecordId");

                    b.Navigation("Creation");

                    b.Navigation("TimeRecord");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.Vacancy", b =>
                {
                    b.HasOne("DasTeamRevolution.Data.Models.RecordCreation", "Creation")
                        .WithMany()
                        .HasForeignKey("CreationId");

                    b.HasOne("DasTeamRevolution.Data.Models.Customer", "Customer")
                        .WithMany("Vacancies")
                        .HasForeignKey("CustomerId");

                    b.HasOne("DasTeamRevolution.Data.Models.RecordModification", "LastModification")
                        .WithMany()
                        .HasForeignKey("LastModificationId");

                    b.HasOne("DasTeamRevolution.Data.Models.PostalAddress", "PostalAddress")
                        .WithMany()
                        .HasForeignKey("PostalAddressId");

                    b.Navigation("Creation");

                    b.Navigation("Customer");

                    b.Navigation("LastModification");

                    b.Navigation("PostalAddress");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.VacancyState", b =>
                {
                    b.HasOne("DasTeamRevolution.Data.Models.RecordCreation", "Creation")
                        .WithMany()
                        .HasForeignKey("CreationId");

                    b.HasOne("DasTeamRevolution.Data.Models.Vacancy", "Vacancy")
                        .WithMany("States")
                        .HasForeignKey("VacancyId");

                    b.Navigation("Creation");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("CustomerUserId");

                    b.Navigation("SupplierUser");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.Assignment", b =>
                {
                    b.Navigation("Rating");

                    b.Navigation("TimeRecords");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.Customer", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.CustomerGroup", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Customers");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.CustomerUser", b =>
                {
                    b.Navigation("Ratings");

                    b.Navigation("TimeRecords");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.Dossier", b =>
                {
                    b.Navigation("States");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.Employee", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Dossiers");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.Order", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.TimeRecord", b =>
                {
                    b.Navigation("States");
                });

            modelBuilder.Entity("DasTeamRevolution.Data.Models.Vacancy", b =>
                {
                    b.Navigation("Dossiers");

                    b.Navigation("States");
                });
#pragma warning restore 612, 618
        }
    }
}
